In [1]:
import pandas as pd
df = pd.read_csv("/content/sample_data/4_허건호02.csv",encoding='UTF8')

In [2]:
df

,화재발생일시,화재발생_연,화재발생_월,화재발생_일,주말여부,화재발생시간대,시군구명,읍면동명,발화지점,날씨,...,출동소요시간,현장소방서거리,현장안전센터거리,현장소방지역대거리,전체인력수합계,화재진압시간,동원장비수,인명피해수,재산피해금액,피해면적
0,2011-01-22 23:35:00,2011,1,22,1,21~24,강릉시,죽헌동,산정상,맑음,...,1700,9,9,0.0,37,1800,8,0,0,0.30
1,2011-01-31 18:13:00,2011,1,31,0,18~21,양양군,현남면,산아래,맑음,...,1615,43,13,0.0,1872,155952,71,0,184330,30.00
2,2011-02-11 17:50:00,2011,2,11,0,15~18,홍천군,내촌면,산중턱,구름많음,...,2240,37,37,7.0,171,20500,9,0,4864,0.30
3,2011-02-12 06:18:00,2011,2,12,1,3~6,원주시,귀래면,산중턱,구름많음,...,2019,20,20,8.0,94,35009,9,0,50,0.30
4,2011-02-26 16:42:00,2011,2,26,1,15~18,원주시,태장동,산정상,맑음,...,508,8,2,0.0,46,3825,8,0,440,0.03
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
534,2021-05-09 13:43:01,2021,5,9,1,12~15,철원군,철원읍,산중턱,맑음,...,801,16,7,0.0,60,2915,12,0,0,0.03
535,2021-05-09 17:44:49,2021,5,9,1,15~18,철원군,철원읍,산정상,맑음,...,347,12,1,0.0,67,4529,13,0,0,0.01
536,2021-05-13 15:37:05,2021,5,13,0,15~18,태백시,하사미동,산중턱,맑음,...,2121,20,17,0.0,144,43459,18,0,0,1.20
537,2021-06-07 15:11:39,2021,6,7,0,15~18,강릉시,주문진읍,산중턱,맑음,...,1344,21,6,0.0,50,12539,11,0,223,0.01
538,2021-06-08 14:52:46,2021,6,8,0,12~15,홍천군,내촌면,산정상,맑음,...,935,26,0,5.0,48,12515,6,0,0,0.04

In [3]:
df.shape

(539, 28)

In [4]:
df.keys

<bound method NDFrame.keys of                   화재발생일시  화재발생_연  화재발생_월  화재발생_일  주말여부 화재발생시간대 시군구명  읍면동명  \
0    2011-01-22 23:35:00    2011       1      22     1   21~24  강릉시   죽헌동
1    2011-01-31 18:13:00    2011       1      31     0   18~21  양양군   현남면
2    2011-02-11 17:50:00    2011       2      11     0   15~18  홍천군   내촌면
3    2011-02-12 06:18:00    2011       2      12     1     3~6  원주시   귀래면
4    2011-02-26 16:42:00    2011       2      26     1   15~18  원주시   태장동
..                   ...     ...     ...     ...   ...     ...  ...   ...
534  2021-05-09 13:43:01    2021       5       9     1   12~15  철원군   철원읍
535  2021-05-09 17:44:49    2021       5       9     1   15~18  철원군   철원읍
536  2021-05-13 15:37:05    2021       5      13     0   15~18  태백시  하사미동
537  2021-06-07 15:11:39    2021       6       7     0   15~18  강릉시  주문진읍
538  2021-06-08 14:52:46    2021       6       8     0   12~15  홍천군   내촌면

    발화지점    날씨  ...  출동소요시간  현장소방서거리  현장안전센터거리 현장소방지역대거리 전체인력수합계  화재진압시간  \
0    산정상    맑음  ...    1700        9         9       0.0      37    1800
1    산아래    맑음  ...    1615       43        13       0.0    1872  155952
2    산중턱  구름많음  ...    2240       37        37       7.0     171   20500
3    산중턱  구름많음  ...    2019       20        20       8.0      94   35009
4    산정상    맑음  ...     508        8         2       0.0      46    3825
..   ...   ...  ...     ...      ...       ...       ...     ...     ...
534  산중턱    맑음  ...     801       16         7       0.0      60    2915
535  산정상    맑음  ...     347       12         1       0.0      67    4529
536  산중턱    맑음  ...    2121       20        17       0.0     144   43459
537  산중턱    맑음  ...    1344       21         6       0.0      50   12539
538  산정상    맑음  ...     935       26         0       5.0      48   12515

    동원장비수 인명피해수  재산피해금액   피해면적
0       8     0       0   0.30
1      71     0  184330  30.00
2       9     0    4864   0.30
3       9     0      50   0.30
4       8     0     440   0.03
..    ...   ...     ...    ...
534    12     0       0   0.03
535    13     0       0   0.01
536    18     0       0   1.20
537    11     0     223   0.01
538     6     0       0   0.04

[539 rows x 28 columns]>

In [5]:
df['피해면적'].shape

(539,)

In [6]:
df['화재발생_월'].shape

(539,)

In [7]:
df['주말여부'].shape

(539,)

In [8]:
df['화재발생시간대'].shape

(539,)

In [9]:
df['시군구명'].shape

(539,)

In [10]:
df['발화지점'].shape

(539,)

In [11]:
df['날씨'].shape

(539,)

In [12]:
df['온도'].shape

(539,)

In [13]:
df['습도'].shape

(539,)

In [14]:
df['발화원인종합'].shape

(539,)

In [15]:
data = df.drop(['화재발생일시','화재발생_연','화재발생_일','읍면동명','시간단위풍속','특보내용','소방서명','서센터명','소방지역대명','출동소요시간','현장소방서거리','현장안전센터거리','현장소방지역대거리','전체인력수합계','화재진압시간','동원장비수','인명피해수','재산피해금액'],axis=1)

In [16]:
data
#분석에 필요한 변수만 남김

     화재발생_월  주말여부 화재발생시간대 시군구명 발화지점    날씨  온도  습도       발화원인종합   피해면적
0         1     1   21~24  강릉시  산정상    맑음  -1  30    방화 및 방화의심   0.30
1         1     0   18~21  양양군  산아래    맑음   1  10      인간의 부주의  30.00
2         2     0   15~18  홍천군  산중턱  구름많음  -2  29      인간의 부주의   0.30
3         2     1     3~6  원주시  산중턱  구름많음  -6  44      인간의 부주의   0.30
4         2     1   15~18  원주시  산정상    맑음  14  23      인간의 부주의   0.03
..      ...   ...     ...  ...  ...   ...  ..  ..          ...    ...
534       5     1   12~15  철원군  산중턱    맑음  19  26      인간의 부주의   0.03
535       5     1   15~18  철원군  산정상    맑음  18  22      인간의 부주의   0.01
536       5     0   15~18  태백시  산중턱    맑음  23  43  기계/전기/화학 요인   1.20
537       6     0   15~18  강릉시  산중턱    맑음  25  62      인간의 부주의   0.01
538       6     0   12~15  홍천군  산정상    맑음  18  78       자연적 요인   0.04

[539 rows x 10 columns]

In [17]:
#Feature 와 target 나누기
features = data[data.columns[:-1]]
target = data[data.columns[-1]]

In [18]:
# 문자열 데이터를 숫자형 데이터로 변환
features = pd.get_dummies(data = features, columns = ['화재발생시간대'], prefix = '화재발생시간대')
features = pd.get_dummies(data = features, columns = ['시군구명'], prefix = '시군구명')
features = pd.get_dummies(data = features, columns = ['발화지점'], prefix = '발화지점')
features = pd.get_dummies(data = features, columns = ['날씨'], prefix = '날씨')
features = pd.get_dummies(data = features, columns = ['발화원인종합'], prefix = '발화원인종합')

In [30]:
#Data split: Train,test
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    features, target, test_size=0.1,random_state = 22
)

In [31]:
print("X_train shape:", X_train.shape)
print("y_train shape:", y_train.shape)

X_train shape: (485, 46)
y_train shape: (485,)

In [32]:
X_train

,화재발생_월,주말여부,온도,습도,화재발생시간대_0~3,화재발생시간대_12~15,화재발생시간대_15~18,화재발생시간대_18~21,화재발생시간대_21~24,화재발생시간대_3~6,...,날씨_구름조금,날씨_맑음,날씨_비,날씨_소나기,날씨_흐림,발화원인종합_기계/전기/화학 요인,발화원인종합_미상,발화원인종합_방화 및 방화의심,발화원인종합_인간의 부주의,발화원인종합_자연적 요인
172,3,0,5,41,0,0,0,1,0,0,...,0,1,0,0,0,0,0,0,1,0
379,11,0,4,26,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,1,0
329,4,0,20,11,0,0,1,0,0,0,...,0,1,0,0,0,0,0,0,1,0
28,11,0,14,63,0,0,1,0,0,0,...,1,0,0,0,0,0,0,0,1,0
137,6,0,23,72,0,0,1,0,0,0,...,0,0,1,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
491,4,0,23,33,1,0,0,0,0,0,...,0,1,0,0,0,0,1,0,0,0
502,10,0,18,51,1,0,0,0,0,0,...,0,1,0,0,0,0,1,0,0,0
358,5,1,20,23,0,0,0,1,0,0,...,0,1,0,0,0,0,0,0,1,0
356,5,1,22,12,0,0,1,0,0,0,...,0,1,0,0,0,0,0,0,1,0
132,5,0,23,30,0,0,0,1,0,0,...,0,1,0,0,0,0,0,0,1,0

In [33]:
print("X_test shape:", X_test.shape)
print("y_test shape:", y_test.shape)

X_test shape: (54, 46)
y_test shape: (54,)

In [34]:
X_test

,화재발생_월,주말여부,온도,습도,화재발생시간대_0~3,화재발생시간대_12~15,화재발생시간대_15~18,화재발생시간대_18~21,화재발생시간대_21~24,화재발생시간대_3~6,...,날씨_구름조금,날씨_맑음,날씨_비,날씨_소나기,날씨_흐림,발화원인종합_기계/전기/화학 요인,발화원인종합_미상,발화원인종합_방화 및 방화의심,발화원인종합_인간의 부주의,발화원인종합_자연적 요인
311,3,1,13,35,0,0,1,0,0,0,...,0,0,1,0,0,0,0,0,1,0
162,3,1,12,14,0,1,0,0,0,0,...,0,1,0,0,0,0,0,0,1,0
325,3,0,18,23,0,0,1,0,0,0,...,1,0,0,0,0,0,0,0,1,0
134,5,1,33,22,0,0,1,0,0,0,...,0,1,0,0,0,0,0,0,1,0
213,6,0,18,65,0,0,0,0,1,0,...,0,1,0,0,0,0,1,0,0,0
432,4,0,7,36,0,0,0,0,0,1,...,0,1,0,0,0,0,0,0,1,0
353,5,1,21,24,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,1,0
360,5,0,25,35,0,1,0,0,0,0,...,0,1,0,0,0,0,0,0,1,0
127,5,1,16,28,0,0,0,1,0,0,...,0,0,1,0,0,0,0,0,1,0
22,4,1,18,22,0,1,0,0,0,0,...,0,1,0,0,0,0,0,0,1,0
123,4,0,23,18,0,0,0,1,0,0,...,0,1,0,0,0,0,0,0,1,0
46,5,0,22,10,0,0,1,0,0,0,...,0,1,0,0,0,0,1,0,0,0
303,1,0,5,37,0,1,0,0,0,0,...,0,1,0,0,0,0,0,0,1,0
89,12,0,7,0,0,1,0,0,0,0,...,1,0,0,0,0,0,1,0,0,0
437,4,1,16,44,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,1,0
158,3,1,12,56,0,1,0,0,0,0,...,0,1,0,0,0,0,0,0,1,0
146,2,1,-10,26,0,1,0,0,0,0,...,0,1,0,0,0,0,0,0,1,0
188,5,1,29,35,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,1,0
299,11,0,4,25,0,0,1,0,0,0,...,0,1,0,0,0,0,0,0,1,0
157,3,1,10,15,0,1,0,0,0,0,...,0,1,0,0,0,0,0,0,1,0
276,4,1,15,35,0,0,1,0,0,0,...,1,0,0,0,0,0,0,0,1,0
528,4,1,20,31,0,1,0,0,0,0,...,0,1,0,0,0,0,0,0,1,0
163,3,1,15,7,0,1,0,0,0,0,...,0,1,0,0,0,0,0,0,1,0
221,6,0,30,43,0,0,1,0,0,0,...,0,1,0,0,0,0,0,0,1,0
30,12,0,-10,73,1,0,0,0,0,0,...,0,1,0,0,0,0,0,0,1,0
255,2,0,-4,65,0,0,1,0,0,0,...,0,0,0,0,1,0,0,0,1,0
480,4,0,11,38,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,1,0
2,2,0,-2,29,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,1,0
166,3,0,8,14,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,1,0
361,5,1,28,33,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,1,0
369,6,0,19,57,0,1,0,0,0,0,...,1,0,0,0,0,0,0,0,1,0
535,5,1,18,22,0,0,1,0,0,0,...,0,1,0,0,0,0,0,0,1,0
492,4,0,24,43,0,0,0,0,0,1,...,0,1,0,0,0,0,0,0,1,0
254,2,0,5,28,0,1,0,0,0,0,...,0,0,0,0,1,0,0,0,1,0
203,5,0,11,98,1,0,0,0,0,0,...,0,1,0,0,0,0,0,0,1,0
300,1,0,1,23,0,1,0,0,0,0,...,0,1,0,0,0,0,0,0,1,0
111,4,0,9,96,0,0,0,0,1,0,...,1,0,0,0,0,0,1,0,0,0
324,3,0,18,20,0,0,1,0,0,0,...,1,0,0,0,0,0,0,0,1,0
206,5,1,21,55,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,1,0
470,2,0,10,45,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,1,0
59,6,0,23,50,0,0,0,0,0,1,...,0,1,0,0,0,0,0,0,1,0
488,4,0,15,26,1,0,0,0,0,0,...,0,1,0,0,0,0,1,0,0,0
434,4,0,16,29,1,0,0,0,0,0,...,0,1,0,0,0,0,0,0,1,0
518,3,0,16,25,0,0,1,0,0,0,...,0,1,0,0,0,0,0,0,1,0
531,5,0,17,46,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,1,0
189,5,1,22,59,0,0,1,0,0,0,...,0,1,0,0,0,0,1,0,0,0
263,3,1,12,16,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,1,0
215,6,0,29,0,0,0,1,0,0,0,...,1,0,0,0,0,0,0,0,1,0
101,3,0,21,27,0,0,1,0,0,0,...,0,1,0,0,0,0,0,0,1,0
482,4,1,15,32,1,0,0,0,0,0,...,0,1,0,0,0,0,0,0,1,0
428,3,0,16,28,1,0,0,0,0,0,...,0,1,0,0,0,0,0,0,1,0
216,6,0,32,31,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,1,0
495,5,0,21,42,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,1,0
512,1,0,-8,59,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,1,0

In [35]:
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import mean_squared_error

model = DecisionTreeRegressor(random_state=22)

model.fit(X_train, y_train)

DecisionTreeRegressor(random_state=22)

In [36]:
y_train_hat = model.predict(X_train)
y_test_hat = model.predict(X_test)

In [37]:
# 모델 성능 평가 결과 training set에 대해서는 성능이 우수하나 test set에 대해서는  성능이 떨어지는 overfitting의 양상을 보임
from sklearn.metrics import mean_squared_error
import numpy as np

rmse_train = np.sqrt(mean_squared_error(y_train, y_train_hat))
rmse_test = np.sqrt(mean_squared_error(y_test, y_test_hat))

print("RMSE on training set:", rmse_train)
print("RMSE on test set:", rmse_test)

RMSE on training set: 1.2202954933216211e-18
RMSE on test set: 36.79251939366661

In [38]:
#GridSearchCV 를 통한 적절한 hyperparameter 찾기
from sklearn.model_selection import GridSearchCV

# 모델 생성
model = DecisionTreeRegressor(random_state=22)

# GridSearchCV 수행을 위한 파라미터 후보군 정의
param_grid = {
    'max_depth': [2, 3, 4, 5, 10, 20],
    'min_samples_split': [2, 3, 4, 5, 12, 13, 14, 15],
    'min_samples_leaf': [1, 2, 3, 4, 5],
}

# GridSearchCV 수행
grid_search = GridSearchCV(model, param_grid=param_grid, cv=5, scoring='neg_mean_squared_error')
grid_search.fit(X_train, y_train)

# 최적의 하이퍼파라미터와 점수 출력
print("Best hyperparameters: ", grid_search.best_params_)
print("Best score: ", -grid_search.best_score_)

Best hyperparameters:  {'max_depth': 3, 'min_samples_leaf': 3, 'min_samples_split': 2}
Best score:  3750.747894172523

In [39]:
model = DecisionTreeRegressor(max_depth=3, min_samples_leaf=3, min_samples_split=2, random_state=22)
model.fit(X_train, y_train)

DecisionTreeRegressor(max_depth=3, min_samples_leaf=3, random_state=22)

In [40]:
y_train_hat = model.predict(X_train)
y_test_hat = model.predict(X_test)

In [41]:
from sklearn.metrics import mean_squared_error
import numpy as np

rmse_train = np.sqrt(mean_squared_error(y_train, y_train_hat))
rmse_test = np.sqrt(mean_squared_error(y_test, y_test_hat))

print("RMSE on training set:", rmse_train)
print("RMSE on test set:", rmse_test)

RMSE on training set: 48.837347972787185
RMSE on test set: 68.04064653029715

In [42]:
#tree 시각화
import graphviz 
from sklearn.tree import export_graphviz

dot_data = export_graphviz(model, out_file=None, 
                           feature_names=X_train.columns,  
                           filled=True, rounded=True,  
                           special_characters=True)  
graph = graphviz.Source(dot_data)  
graph.render("tree", format='png')  
graph